require-stack-version: ">= 2.1.3"
resolver: lts-9.18
extra-deps:
- url: https://github.com/da-x/gitlib/archive/5b338169a2618337a60aaf17e2ab56a2654b1244.zip
  subdirs:
  - gitlib
  - gitlib-libgit2
  - hlibgit2
