resolver: lts-5.0
packages:
- location:
    git: https://github.com/da-x/gitlib
    commit: 5b338169a2618337a60aaf17e2ab56a2654b1244
  extra-dep: true
  subdirs:
  - gitlib
  - gitlib-libgit2
  - hlibgit2
- .
