require-stack-version: ">= 2.1.3"
resolver: lts-11.22
extra-deps:
- url: https://github.com/da-x/gitlib/archive/eef462541c68be62e6cbc5ac4595114bd6f67233.tar.gz
  subdirs:
  - gitlib
  - gitlib-libgit2
  - hlibgit2
