#!/bin/bash

#
# Scripts that prepares the binary Mac OS X installation and its
# relevant Homebrew file.
#

pkgname=fancydiff
pkgtitle="Fancy coloring of diffs for Git"
homeurl=http://github.com/da-x/fancydiff

t=$(dirname ${BASH_SOURCE[0]})
stack_params="--extra-include-dirs=/usr/local/opt/icu4c/include \
        --extra-lib-dirs=/usr/local/opt/icu4c/lib \
        --extra-include-dirs=/usr/local/opt/openssl/include \
        --extra-lib-dirs=/usr/local/opt/openssl/lib"

set -e
set -u

prep-exe() {
    brew install icu4c
    brew install openssl

    cd ${t}
    stack setup ${stack_params}
    stack build ${stack_params}
    cd - > /dev/null
}

pack() {
    exe_path=$(cd ${t}/.. && stack exec -- which fancydiff)

    rm -rf ${t}/PACK
    mkdir ${t}/PACK
    ver=$(${t}/../version.sh tag-with-simple | awk -F" " '{print $1}')

    tarball=${pkgname}-${ver}-darwin
    pdir=${t}/PACK/${tarball}

    mkdir -p ${pdir}/bin
    cat - > ${pdir}/bin/fancydiff <<EOF
#!/bin/bash

t=\${BASH_SOURCE[0]}
d=\$(dirname \${t})
dl=\$(dirname \${d})/deps
export DYLD_LIBRARY_PATH=\${dl}
exec \${d}/../exe/fancydiff "\$@"

EOF
    chmod a+x ${pdir}/bin/fancydiff
    mkdir -p ${pdir}/deps

    for i in $(otool -L ${exe_path} | grep /usr/local | awk -F" " '{print $1}') ; do
	d=$(dirname ${i})
	b=$(basename ${i})
	for j in $(ls -1 ${d}) ; do
	    if [[ "$(readlink $d/$j)" == "$b" ]] ; then
		ln -s ${b} ${pdir}/deps/${j}
	    fi
	done
	cp $i ${pdir}/deps
    done

    mkdir -p ${pdir}/exe
    cp -a ${exe_path} ${pdir}/exe/fancydiff
    cp -a ${t}/../LICENSE ${pdir}/LICENSE.txt

    cp -a ${t}/../doc ${pdir}/doc
    cp -a ${t}/../README.md ${pdir}

    packfile=${pkgname}-${ver}-darwin-x86_64.tar.gz
    packfile_abs=${t}/PACK/${packfile}
    cd ${t}/PACK
    tar -cvzf ${packfile} ${tarball}
    cd - > /dev/null
    rm -rf ${pdir}
}

localtest=false

local-test() {
    localtest=true
}

mk-brew-formula() {
    sum=$(shasum -a 256 ${packfile_abs} | awk -F" " '{print $1}')
    tag=$(${t}/../version.sh tag)

    if [[ "$localtest" == "true" ]] ; then
	fileurl="file://`pwd`/packaging/PACK/${packfile}"
    else
	fileurl="${homeurl}/releases/download/v${tag}/${packfile}"
    fi

    cat - > ${t}/PACK/fancydiff.rb  <<EOF

class Fancydiff < Formula
  desc "${pkgtitle}"
  homepage "${homeurl}"
  url "${fileurl}"
  sha256 "${sum}"
  version "${tag}"

  depends_on :arch => :x86_64

  bottle :unneeded

  def install
    doc.install Dir["doc/*", "README.md", "LICENSE.txt"]
    libexec.install Dir["bin", "exe", "deps"]
    bin.write_exec_script Dir["#{libexec}/bin/*"]
  end
end

EOF
}

brew-test() {
    brew install ${t}/PACK/fancydiff.rb
}

if [[ `uname -s` != "Darwin" ]] ; then
    echo "Designed to run on Darwin"
    exit -1
fi

case "$@" in
    test)
	prep-exe
	local-test
	pack
	mk-brew-formula
	brew-test
        ;;
    release)
	prep-exe
	pack
	mk-brew-formula
        ;;
    *)
	echo "$@"
        for i in "$@" ; do
            $i
        done
        ;;
esac
